Update git:// github.com submodule URL to use https://
voxpupuli/puppet-augeasproviders_shellvar pull request #50
Opened 2023-01-17 15:06 UTC by ruleant

Pull Request (PR) description

github.com permanently disabled unencrypted git on 15/3/22: https://github.blog/2021-09-01-improving-git-protocol-security-github/, which means that updating this repository's submodules currently fails.

This PR changes the submodule URL in question to an equivalent HTTPS URL that works.

cf. https://github.com/voxpupuli/puppet-augeasproviders_core/pull/38

This Pull Request (PR) fixes the following issues

n/a

2023-01-17 17:49 UTC, ekohl requested changes
Actually, I think it may not be needed at all. So I think you can simply delete the `.gitmodules` file.

2023-01-18 09:37 UTC, ruleant commented
I can remove it if you like. Just not sure if it is ok to do. I don't know this module well enough to make that call.

2023-01-18 09:56 UTC, ekohl commented
I would say that if CI passes, then it should be safe to do so. It's only used for testing and doesn't end up in the resulting module on the forge.

2023-01-18 14:18 UTC, ruleant commented
The submodule was removed.

2023-01-18 14:43 UTC, ekohl approved these changes
Thanks!

2023-01-18 14:43 UTC, merged